{"uid":"8da088efed6ccbc2","name":"Test create user","fullName":"tests.test_users.TestUsersAPI#test_create_user","historyId":"7906fed064abe2a7a41f166381015ab4","time":{"start":1733116329089,"stop":1733116329089,"duration":0},"description":"Verify user creation and data validation","descriptionHtml":"<p>Verify user creation and data validation</p>\n","status":"failed","statusMessage":"AssertionError: User data validation failed: 1 validation error for UserResponse\nnickname\n  String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/string_too_short","statusTrace":"self = <tests.test_users.TestUsersAPI object at 0x7f8fa2ff4950>\nnew_user = {'avatar_url': '', 'email': 'suarezjames@example.com', 'name': 'Bonnie', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n>               UserResponse.model_validate(user)\nE               pydantic_core._pydantic_core.ValidationError: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:112: ValidationError\n\nThe above exception was the direct cause of the following exception:\n\nself = <tests.test_users.TestUsersAPI object at 0x7f8fa2ff4950>\nnew_user = {'avatar_url': '', 'email': 'suarezjames@example.com', 'name': 'Bonnie', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n                UserResponse.model_validate(user)\n            except ValidationError as e:\n                msg = f\"User data validation failed: {e}\"\n>               raise AssertionError(msg) from e\nE               AssertionError: User data validation failed: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:115: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"pytestconfig","time":{"start":1733116321555,"stop":1733116321555,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1733116321556,"stop":1733116321556,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1733116321556,"stop":1733116321556,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_session_faker","time":{"start":1733116321556,"stop":1733116321557,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1733116321556,"stop":1733116321556,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright","time":{"start":1733116321557,"stop":1733116321794,"duration":237},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_request_context","time":{"start":1733116321795,"stop":1733116321802,"duration":7},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_api_client","time":{"start":1733116328601,"stop":1733116328601,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"new_user","time":{"start":1733116328601,"stop":1733116329088,"duration":487},"status":"passed","steps":[],"attachments":[{"uid":"b014012f8c6b9dfc","name":"API Response","source":"b014012f8c6b9dfc.txt","type":"text/plain","size":158},{"uid":"3da8ab2b48f18e8f","name":"Status Code","source":"3da8ab2b48f18e8f.txt","type":"text/plain","size":3},{"uid":"9738f136701e6f15","name":"Headers","source":"9738f136701e6f15.txt","type":"text/plain","size":648},{"uid":"60facf65b42d1031","name":"URL","source":"60facf65b42d1031.txt","type":"text/plain","size":45}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":4,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Verify user creation and data validation","status":"failed","statusMessage":"AssertionError: User data validation failed: 1 validation error for UserResponse\nnickname\n  String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/string_too_short","statusTrace":"self = <tests.test_users.TestUsersAPI object at 0x7f8fa2ff4950>\nnew_user = {'avatar_url': '', 'email': 'suarezjames@example.com', 'name': 'Bonnie', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n>               UserResponse.model_validate(user)\nE               pydantic_core._pydantic_core.ValidationError: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:112: ValidationError\n\nThe above exception was the direct cause of the following exception:\n\nself = <tests.test_users.TestUsersAPI object at 0x7f8fa2ff4950>\nnew_user = {'avatar_url': '', 'email': 'suarezjames@example.com', 'name': 'Bonnie', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n                UserResponse.model_validate(user)\n            except ValidationError as e:\n                msg = f\"User data validation failed: {e}\"\n>               raise AssertionError(msg) from e\nE               AssertionError: User data validation failed: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:115: AssertionError","steps":[{"name":"Validating newly created user data","time":{"start":1733116329089,"stop":1733116329089,"duration":0},"status":"failed","statusMessage":"AssertionError: User data validation failed: 1 validation error for UserResponse\nnickname\n  String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n","statusTrace":"  File \"/home/runner/work/qa-hackathon-raptors/qa-hackathon-raptors/tests/test_users.py\", line 115, in test_create_user\n    raise AssertionError(msg) from e\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"new_user::0","time":{"start":1733116329094,"stop":1733116329885,"duration":791},"status":"passed","steps":[],"attachments":[{"uid":"4f113d56582d2ac0","name":"API Response","source":"4f113d56582d2ac0.txt","type":"text/plain","size":14},{"uid":"56e98032d675d8b3","name":"Status Code","source":"56e98032d675d8b3.txt","type":"text/plain","size":3},{"uid":"ec18d9e2752cfbf5","name":"Headers","source":"ec18d9e2752cfbf5.txt","type":"text/plain","size":578},{"uid":"119bd0c5f7eed110","name":"URL","source":"119bd0c5f7eed110.txt","type":"text/plain","size":82}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":4,"hasContent":true,"attachmentStep":false},{"name":"api_request_context::0","time":{"start":1733116338218,"stop":1733116338221,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright::0","time":{"start":1733116338221,"stop":1733116338227,"duration":6},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"User Management"},{"name":"feature","value":"User API Operations"},{"name":"severity","value":"critical"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_users"},{"name":"subSuite","value":"TestUsersAPI"},{"name":"host","value":"fv-az692-554"},{"name":"thread","value":"5498-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"new_user","value":"'api-3'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"8da088efed6ccbc2.json","parameterValues":["'api-3'"]}